### ISSUE TITLE
golang vs openresty

### ISSUE THREAD

**Issue by wzhsh90** [shixinke/lua-resty-ip2region#5]
method: BtreeSearch ip:125.81.12.166

test method: ab -c 1000 -n 10000 http://localhost:8080/wx/account/ip 

1、this is my golang test result
![image](https://user-images.githubusercontent.com/16187191/42924240-d9217b36-8b5b-11e8-848e-d706a1872663.png)

2、this is my openresty test result 

![image](https://user-images.githubusercontent.com/16187191/42924323-354a0b1c-8b5c-11e8-938e-769fc70c0a50.png)

 golang works better than openresty

**Comment by shixinke** [comment]
Thank you for your attention and message.
This library contains a lot of IO operations and CPU calculations.In a production environment, the configuration option of lua_code_cache  needs to be set to on.The following is my test results:

My stress test tool is **wrk**.

#### Golang

golang demo code:

```
package main

import (
	"fmt"
	"net/http"

	"github.com/mohong122/ip2region/binding/golang/ip2region"
)

func handler(w http.ResponseWriter, r *http.Request) {
	region, err := ip2region.New("src/github.com/mohong122/ip2region/data/ip2region.db")
	defer region.Close()
	if err != nil {
		fmt.Println(err)
		return
	}

	ip, err := region.BtreeSearch("125.81.12.166")
	if err != nil {
		w.Write([]byte("not found"))
	} else {
		var resp string = ""
		resp = ip.Country + " " + ip.Region + " " + ip.Province + " "+ip.City + " "+ ip.ISP
		w.Write([]byte(resp))
	}

}

func main() {
	http.HandleFunc("/iplocation", handler)
	err := http.ListenAndServe(":8888", nil)
	if err != nil {
		fmt.Printf("http error:%v", err)
	}

}
```

I am using a standard library instead of a beego framework.

```
wrk -c 10000 -t 10 -d 30s http://localhost:8888/iplocation --timeout 30s
```

golang result:

```
Running 30s test @ http://localhost:8888/iplocation
  10 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    16.57ms   20.40ms 251.58ms   87.05%
    Req/Sec     6.81k     3.24k   13.80k    60.37%
  1828965 requests in 30.04s, 273.85MB read
  Socket errors: connect 8989, read 0, write 0, timeout 0
Requests/sec:  60879.19
Transfer/sec:      9.12MB

```

#### OpenResty

1.When nginx's configuration option worker_process is set to 1, the result is as follows:

wrk -c 10000 -t 10 -d 30s http://localhost/iplocation --timeout 30s


```Running 30s test @ http://localhost/iplocation
  10 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    40.12ms  307.92ms  17.43s    99.15%
    Req/Sec     2.06k     1.09k    6.13k    63.82%
  576220 requests in 30.10s, 131.31MB read
  Socket errors: connect 0, read 2972, write 0, timeout 0
Requests/sec:  19145.30
Transfer/sec:      4.36MB
```

2.When nginx's configuration option worker_process is set to 8(My computer has 8 processor), the result is as follows:

```
Running 30s test @ http://localhost/iplocation
  10 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    40.54ms  137.43ms  28.63s    99.17%
    Req/Sec     7.20k     2.14k   35.41k    68.55%
  2138083 requests in 30.10s, 487.23MB read
  Socket errors: connect 0, read 2375, write 0, timeout 0
Requests/sec:  71032.20
Transfer/sec:     16.19MB

```

Therefore, it doesn't make sense to say what language performance is good. It depends on the context, which language is more suitable.

**Comment by dearplain** [comment]
```
func handler(w http.ResponseWriter, r *http.Request) {
	region, err := ip2region.New("src/github.com/mohong122/ip2region/data/ip2region.db")
	defer region.Close()
```
new ip2region on every request? stupid benmark.
